name: CLoIT Auto Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into the server and manage services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deploying changes"
            cd /home/ubuntu/CLoIT
            
            # Pull changes from master
            git pull
            
            # Stop and start PM2
            sudo pm2 restart quasar-app
